server:
  port: 5000
  
spring:
  datasource:
    url: jdbc:mysql://IP:3306/databaseName?useUnicode=true&charset=UTF-8&useAffectedRows=true&useSSL=false
    username: your name
    password: your password
    driver-class-name: com.mysql.jdbc.Driver
    
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.noel.handbook.accesscontroll.model
